[package]
name = "flare"
version = "0.1.0"
edition = "2024"

[features]
default = ["soulver"]
debug = ["iced/debug"]
soulver = []

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# pinned to latest commit as of 2025-11-21
iced = { git = "https://github.com/iced-rs/iced", rev = "8bfd099c5929d927a3fdde666d4c645d0bd83cb7", features = ["advanced", "canvas", "image", "markdown", "svg", "tokio", "wgpu"] }
reqwest = { version = "0.12.8", features = ["blocking", "rustls-tls"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "net", "sync", "process"] }
phf = { version = "0.13.1", features = ["macros"] }
rmp-serde = "1.3.0"
dirs = "6.0.0"
webbrowser = "1.0.6"
arboard = { version = "3.6.1", features = ["wayland-data-control", "image-data"] }
walkdir = "2.5.0"
rayon = "1.11.0"
which = "8.0.0"
rust-ini = "0.21"
freedesktop-icons = "0.4.0"
blake3 = "1.8.2"
url = "2.5.7"
rand = "0.9.2"
keyring = { version = "3.6.3", features = ["sync-secret-service"] }
chacha20poly1305 = "0.10.1"
hex = "0.4.3"
chrono = "0.4.42"
image = "0.25.9"
base64 = "0.22.1"

# implementation ~stolen~ inspired by Tauri - we probably don't need this
[target.'cfg(windows)'.dependencies]
dunce = "1"
windows-registry = "0.5"

[target.'cfg(target_os = "linux")'.dependencies]
rust-ini = "0.21"
iced_layershell = { git = "https://github.com/ByteAtATime/exwlshelleventloop" }
